// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SisRh.Infra.Data.Context;
using System;

namespace SisRh.Infra.Data.Context.Migrations
{
    [DbContext(typeof(SisRhContext))]
    [Migration("20180307175237_AddCpfEmpregado")]
    partial class AddCpfEmpregado
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SisRh.Domain.Entities.Beneficio", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Codigo");

                    b.ToTable("Beneficio");
                });

            modelBuilder.Entity("SisRh.Domain.Entities.Empregado", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CodSetor");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11);

                    b.Property<DateTime>("DataNasc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("TelCelular")
                        .HasMaxLength(20);

                    b.Property<string>("TelResidencial")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Codigo");

                    b.HasIndex("CodSetor");

                    b.ToTable("Empregado");
                });

            modelBuilder.Entity("SisRh.Domain.Entities.EmpregadoBeneficio", b =>
                {
                    b.Property<int>("CodEmpregado");

                    b.Property<int>("CodBeneficio");

                    b.HasKey("CodEmpregado", "CodBeneficio");

                    b.HasIndex("CodBeneficio");

                    b.ToTable("EmpregadoBeneficio");
                });

            modelBuilder.Entity("SisRh.Domain.Entities.Setor", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.HasKey("Codigo");

                    b.ToTable("Setor");
                });

            modelBuilder.Entity("SisRh.Domain.Entities.Empregado", b =>
                {
                    b.HasOne("SisRh.Domain.Entities.Setor", "Setor")
                        .WithMany("Empregados")
                        .HasForeignKey("CodSetor")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SisRh.Domain.Entities.EmpregadoBeneficio", b =>
                {
                    b.HasOne("SisRh.Domain.Entities.Beneficio", "Beneficio")
                        .WithMany("EmpregadoBeneficios")
                        .HasForeignKey("CodBeneficio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisRh.Domain.Entities.Empregado", "Empregado")
                        .WithMany("EmpregadoBeneficios")
                        .HasForeignKey("CodEmpregado")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
