//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisRh.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagemResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagemResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SisRh.WEB.Resources.MensagemResource", typeof(MensagemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo inválido..
        /// </summary>
        public static string MSG_CAMPO_INVALIDO {
            get {
                return ResourceManager.GetString("MSG_CAMPO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo deve conter até {MaxLength} caracteres..
        /// </summary>
        public static string MSG_CAMPO_MAX_LEN {
            get {
                return ResourceManager.GetString("MSG_CAMPO_MAX_LEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório..
        /// </summary>
        public static string MSG_CAMPO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("MSG_CAMPO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe pelo menos um número de telefone..
        /// </summary>
        public static string MSG_INFORME_TELEFONE {
            get {
                return ResourceManager.GetString("MSG_INFORME_TELEFONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro atualizado com sucesso..
        /// </summary>
        public static string MSG_REGISTRO_ATUALIZADO_SUCESSO {
            get {
                return ResourceManager.GetString("MSG_REGISTRO_ATUALIZADO_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro excluído com sucesso..
        /// </summary>
        public static string MSG_REGISTRO_EXCLUIDO_SUCESSO {
            get {
                return ResourceManager.GetString("MSG_REGISTRO_EXCLUIDO_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro inserido com sucesso..
        /// </summary>
        public static string MSG_REGISTRO_INSERIDO_SUCESSO {
            get {
                return ResourceManager.GetString("MSG_REGISTRO_INSERIDO_SUCESSO", resourceCulture);
            }
        }
    }
}
